spring.application.name=jwttoken

spring.datasource.url=jdbc:mysql://localhost:3306/security
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.security.user.name=kevin
spring.security.user.password=pass

jwt.secretKey = fk4b3h45lv7kh254fg5b43641f634rtv6147c4hc3u9zrg51rv5fvb144v4144rv575414v44