spring.application.name=bloodmanagementproject

spring.datasource.url=jdbc:mysql://localhost:3306/blood
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kevingothadiya1305@gmail.com
spring.mail.password=nqyjvxryikletnaq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Frontend base URL for reset link
app.frontend.url=http://localhost:4200
